// Generated by CoffeeScript 1.3.1
(function() {
  var dropbox, failure, success;

  dropbox = new Dropbox;

  success = function(response) {
    return console.log(response);
  };

  failure = function(response) {
    return console.log("Error", response);
  };

  dropbox.authorize(function() {
    dropbox.metadata().then(success).fail(failure);
    dropbox.search("", {
      query: "me.jpg"
    }).then(success).fail(failure);
    return dropbox.put_file("example.txt", null, "text content").then(success).fail(failure);
  });

}).call(this);
