// Generated by CoffeeScript 1.3.1
(function() {
  var dropbox, failure;

  dropbox = new Dropbox;

  failure = function(response) {
    return console.log("Error", response);
  };

  dropbox.authorize(function() {
    var params;
    dropbox.metadata(function(data) {
      return console.log(data);
    }, failure);
    params = {
      query: "me.jpg"
    };
    dropbox.search(function(data) {
      return console.log(data);
    }, failure, null, params);
    return dropbox.put_file(function(data) {
      return console.log(data);
    }, failure, "example.txt", null, "text content");
  });

}).call(this);
