// Generated by CoffeeScript 1.3.1
(function() {
  var dropbox;

  dropbox = new Dropbox("dropbox");

  dropbox.authorize().then(function() {
    chrome.omnibox.setDefaultSuggestion({
      description: "Search Dropbox"
    });
    chrome.omnibox.onInputChanged.addListener(function(text, suggest) {
      var textPattern;
      if (text) {
        textPattern = new RegExp(text, "g");
        return dropbox.search("/", {
          query: text,
          file_limit: 5
        }).then(function(results) {
          var description, path, result, suggestions, _i, _len;
          suggestions = [];
          for (_i = 0, _len = results.length; _i < _len; _i++) {
            result = results[_i];
            path = result.path.replace(/^\//, "");
            description = path.replace(textPattern, function(match) {
              return "<match>" + match + "</match>";
            });
            description = "<url>" + description + "</url>";
            if (!result.is_dir) {
              description += " - <dim>" + result.size + "</dim>";
            }
            suggestions.push({
              content: path,
              description: description
            });
          }
          return suggest(suggestions);
        });
      }
    });
    return chrome.omnibox.onInputEntered.addListener(function(text) {
      return dropbox.shares(text).then(function(response) {
        if (response.url) {
          return window.open(response.url);
        }
      });
    });
  });

}).call(this);
