// Generated by CoffeeScript 1.3.1
(function() {
  var CONSUMER_KEY, CONSUMER_SECRET, dropbox, getDate;

  CONSUMER_KEY = "87l32mwer3wakeq";

  CONSUMER_SECRET = "tq9g12fobgymyqz";

  dropbox = new Dropbox(CONSUMER_KEY, CONSUMER_SECRET);

  getDate = function() {
    var day, month, today, year;
    today = new Date;
    year = today.getFullYear();
    month = today.getMonth() + 1;
    day = today.getDate();
    if (month < 10) {
      month = "0" + month;
    }
    if (day < 10) {
      day = "0" + day;
    }
    return "" + year + "-" + month + "-" + day;
  };

  dropbox.authorize().then(function() {
    return chrome.tabs.getSelected(null, function(tab) {
      return chrome.pageCapture.saveAsMHTML({
        tabId: tab.id
      }, function(data) {
        var reader;
        reader = new FileReader;
        reader.onload = function(e) {
          var date, headers, params, title;
          title = tab.title || tab.url.split("?")[0];
          date = getDate();
          title += " - [" + date + "]";
          alert(title);
          params = {
            overwrite: "false"
          };
          headers = {
            "Content-Type": "multipart/related"
          };
          return dropbox.put_file(title, params, this.result, headers);
        };
        return reader.readAsBinaryString(data);
      });
    });
  });

}).call(this);
